apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-capture
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: tcpdump
        image: tls-anom/traffic-capture
        securityContext:
          privileged: true
        volumeMounts:
        - name: pcap
          mountPath: /pcap
      volumes:
      - name: pcap
        persistentVolumeClaim:
          claimName: pcap-pvc
